packwiz cf add https://www.curseforge.com/minecraft/mc-mods/new-world-height-and-depth
packwiz cf add https://www.curseforge.com/minecraft/mc-mods/nether-remastered
packwiz cf add https://www.curseforge.com/minecraft/mc-mods/biomesize
packwiz cf add https://www.curseforge.com/minecraft/mc-mods/deeper-nether-biomes
packwiz cf add https://www.curseforge.com/minecraft/mc-mods/continents
packwiz cf add https://www.curseforge.com/minecraft/mc-mods/ferdinands-flowers
packwiz cf add https://www.curseforge.com/minecraft/mc-mods/large-ore-deposits
packwiz cf add https://www.curseforge.com/minecraft/mc-mods/rings-of-ascension
packwiz cf add https://www.curseforge.com/minecraft/mc-mods/travelers-titles
packwiz cf add https://www.curseforge.com/minecraft/mc-mods/endremastered